"""Initial schema

Revision ID: 390eae8db71b
Revises: 
Create Date: 2025-09-22 18:10:03.187022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390eae8db71b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_base_url', sa.String(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_configurations_id'), 'ai_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_configurations_model_name'), 'ai_configurations', ['model_name'], unique=True)
    op.create_table('memory_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_conversation_id'), 'memory_entries', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_id'), 'memory_entries', ['id'], unique=False)
    op.create_index(op.f('ix_memory_entries_session_id'), 'memory_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_timestamp'), 'memory_entries', ['timestamp'], unique=False)
    op.create_table('prompt_chains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=True),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_chains_id'), 'prompt_chains', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_chains_name'), 'prompt_chains', ['name'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('template_content', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=True)
    op.create_table('generated_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('input_variables', sa.JSON(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_id'), 'generated_content', ['id'], unique=False)
    op.create_index(op.f('ix_generated_content_prompt_id'), 'generated_content', ['prompt_id'], unique=False)
    op.create_table('prompt_chain_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['prompt_chains.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_chain_executions_chain_id'), 'prompt_chain_executions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_prompt_chain_executions_execution_id'), 'prompt_chain_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_prompt_chain_executions_id'), 'prompt_chain_executions', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_chain_executions_prompt_id'), 'prompt_chain_executions', ['prompt_id'], unique=False)
    op.create_table('prompt_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_usage_id'), 'prompt_usage', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_usage_prompt_id'), 'prompt_usage', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_usage_prompt_id'), table_name='prompt_usage')
    op.drop_index(op.f('ix_prompt_usage_id'), table_name='prompt_usage')
    op.drop_table('prompt_usage')
    op.drop_index(op.f('ix_prompt_chain_executions_prompt_id'), table_name='prompt_chain_executions')
    op.drop_index(op.f('ix_prompt_chain_executions_id'), table_name='prompt_chain_executions')
    op.drop_index(op.f('ix_prompt_chain_executions_execution_id'), table_name='prompt_chain_executions')
    op.drop_index(op.f('ix_prompt_chain_executions_chain_id'), table_name='prompt_chain_executions')
    op.drop_table('prompt_chain_executions')
    op.drop_index(op.f('ix_generated_content_prompt_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_prompt_chains_name'), table_name='prompt_chains')
    op.drop_index(op.f('ix_prompt_chains_id'), table_name='prompt_chains')
    op.drop_table('prompt_chains')
    op.drop_index(op.f('ix_memory_entries_timestamp'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_session_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_conversation_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_ai_configurations_model_name'), table_name='ai_configurations')
    op.drop_index(op.f('ix_ai_configurations_id'), table_name='ai_configurations')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###
